# Cloudflare Pages configuration
name = "plumberindarlington-co-uk"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-20"

[[d1_databases]]
binding = "DB"
database_name = "darlington-leads"
database_id = "172ad0e2-3852-4854-a886-53b790d1327f"
